### ISSUE TITLE
Ycm无法启动server端

### ISSUE THREAD

**Issue by liangcha-ck** [snakeleon/YouCompleteMe-x86#1]
# 错误日志

**gvim报错：**
The ycmd server SHUT DOWN (restart with 'YcmRestartServer'). Run ':YcmToggleLogs stderr' to check Restarting ycmd server...

**YcmToggleLogs stderr错误信息：**
Main()
  File "D:\PROGRA~2\Vim\vimfiles\bundle\YOUCOM~1\THIRD_~1\ycmd\ycmd__main__.py", line 158, in Main
    if not CompatibleWithCurrentCoreVersion():
  File "D:\PROGRA~2\Vim\vimfiles\bundle\YOUCOM~1\THIRD_~1\ycmd\ycmd\server_utils.py", line 50, in CompatibleWithCurrentCoreVersion
    import ycm_core
ImportError: DLL load failed: 拒绝访问。
# 使用环境

OS：win7 32bit
vim版本：VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:38:33)
ycm版本：ycmd 核心版本: 19 (29 February 2016) 静态编译
clang 版本: 3.7.1 (5 January 2016) Clang

**Comment by snakeleon** [comment]
从日志看，似乎是核心版本不兼容引起的，查看一下你启动vim后，在windows任务管理器中查看有没有python.exe的进程，然后在vim中执行 :python print("Hello World!")，是否能正常调用python指令？如果都排除这些问题，请问你的Python安装的版本是多少？（我是用python 2.7.11的静态库编译的，是否这里引起的不兼容）

**Comment by liangcha-ck** [comment]
命令python 'hello,world' 运行正常,python版本是2.7.10，如果用2.7.11官方编译的vim会闪退，应该是版本不兼容的原因。
使用了你推介的vim版本用11版的python后vim不会闪退了，但是所有使用python插件不能加载了，运行pyhton 'hello,world'也是失败的。

日志：
Error detected while processing F:\Vim\bundle\YouCompleteMe\autoload\youcompletme.vim:
line 691:
E887: Sorry, this command is disabled, the Python's site module could not be load.
Error detected while processing function you completeme#Enable[10]..<SNR>97_SetUpPython:
line 34:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.

**Comment by snakeleon** [comment]
据vim_dev的记录，这是Python2.7.11的已知BUG. Vim以2.7.11版编译支持特性后会找不到Python的环境变量。
解决方法是修改注册表键值：
将注册表键值
HKLM_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7
修改为
HKLM_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7-32
以上，Python新版便可在Vim里很好的工作。
最好的方法是：
将HKLM_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7 整个键值导出，用文本编辑器打开将2.7替换为2.7-32后保存，再导入。这样保留原来的键值以避免其它编译环境找不到python的环境或者环境不一致的问题。

**Comment by liangcha-ck** [comment]
多谢。我稍后试试。

目前我用python2.7.10 和 http://tuxproject.de/projects/vim/complete-x86.7z 这个版本vim也能正常运行了。

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar  1 2016 20:35:40)
MS-Windows 32-bit console version
Included patches: 1-1467
Compiled by hp@HP-PC
